"""Optional PostgreSQL state backend for :class:`hermes_state.SessionDB`.

This module holds *all* PostgreSQL-specific code for the session/state store so
that ``hermes_state.py`` carries only a handful of small dispatch seams. SQLite
remains the default backend; nothing here is imported unless the operator
explicitly selects ``sessions.state_backend = "postgres"``.

Design contract (kept deliberately narrow):

* A thin cursor adapter (:class:`_PostgresConnection` / :class:`_PostgresCursor`)
  translates only the *closed* set of SQLite idioms the ``SessionDB`` class
  emits at its write/read sites: ``?`` -> ``%s``, ``BEGIN IMMEDIATE`` ->
  ``BEGIN``, ``INSERT OR IGNORE`` -> ``INSERT ... ON CONFLICT DO NOTHING``, and
  ``RETURNING id`` synthesis so ``cursor.lastrowid`` keeps working on message
  inserts. Everything else passes through untouched.
* Queries that cannot be mechanically translated (full-text search, the
  compression-lock acquisition, migration imports) are purpose-built methods
  here, dispatched from explicit seams in ``SessionDB``.
* The connection string (DSN) is passed through to the driver unchanged, so
  TLS mode, host, port, and credentials all come from the operator's DSN.

The driver dependency (``psycopg``) is optional and imported lazily; a base
install without the ``postgres`` extra never imports this module.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------
#
# Mirrors the SQLite schema in hermes_state.SCHEMA_SQL column-for-column so the
# adapter can run the same SessionDB queries unchanged. Dialect differences:
#   * INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS
#     IDENTITY PRIMARY KEY (server-assigned monotonic id; migration may also
#     supply explicit ids, hence BY DEFAULT not ALWAYS).
#   * REAL                               -> DOUBLE PRECISION
#   * No FTS5 virtual tables (PostgreSQL has no fts5; search uses ILIKE,
#     accelerated by pg_trgm GIN indexes when pg_trgm is installed — see
#     _PG_ONLY_MIGRATIONS / apply_postgres_migrations).
# The integer/boolean flag columns (observed, active, archived, rewind_count)
# stay INTEGER to match how SessionDB writes and filters them (``active = 1``).

SCHEMA_SQL_POSTGRES = """
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    user_id TEXT,
    model TEXT,
    model_config TEXT,
    system_prompt TEXT,
    parent_session_id TEXT,
    started_at DOUBLE PRECISION NOT NULL,
    ended_at DOUBLE PRECISION,
    end_reason TEXT,
    message_count INTEGER DEFAULT 0,
    tool_call_count INTEGER DEFAULT 0,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_write_tokens INTEGER DEFAULT 0,
    reasoning_tokens INTEGER DEFAULT 0,
    cwd TEXT,
    billing_provider TEXT,
    billing_base_url TEXT,
    billing_mode TEXT,
    estimated_cost_usd DOUBLE PRECISION,
    actual_cost_usd DOUBLE PRECISION,
    cost_status TEXT,
    cost_source TEXT,
    pricing_version TEXT,
    title TEXT,
    api_call_count INTEGER DEFAULT 0,
    handoff_state TEXT,
    handoff_platform TEXT,
    handoff_error TEXT,
    rewind_count INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (parent_session_id) REFERENCES sessions(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    role TEXT NOT NULL,
    content TEXT,
    tool_call_id TEXT,
    tool_calls TEXT,
    tool_name TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    token_count INTEGER,
    finish_reason TEXT,
    reasoning TEXT,
    reasoning_content TEXT,
    reasoning_details TEXT,
    codex_reasoning_items TEXT,
    codex_message_items TEXT,
    platform_message_id TEXT,
    observed INTEGER DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS state_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS compression_locks (
    session_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_source ON sessions(source);
CREATE INDEX IF NOT EXISTS idx_sessions_source_id ON sessions(source, id);
CREATE INDEX IF NOT EXISTS idx_sessions_parent ON sessions(parent_session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_messages_session_active
    ON messages(session_id, active, timestamp);
CREATE INDEX IF NOT EXISTS idx_compression_locks_expires
    ON compression_locks(expires_at);
"""


@dataclass(frozen=True)
class StateDatabaseConfig:
    """Resolved session/state database configuration."""

    backend: str
    db_path: Any
    database_url: Optional[str] = None


# ---------------------------------------------------------------------------
# Postgres-only migrations (version > upstream SCHEMA_VERSION=16)
# ---------------------------------------------------------------------------
#
# These migrations extend the Postgres schema beyond what the upstream SQLite
# path knows about. Version numbers > 16 are Postgres-local and will never
# conflict with the SQLite migration path.
#
# schema_version is append-only: one row per applied migration. Every read
# uses MAX(version) (see postgres_schema_version) so ordering is unambiguous.


@dataclass(frozen=True)
class PostgresMigration:
    """A single Postgres-only schema migration step.

    ``version``: Postgres-local version number (may exceed the upstream
        SCHEMA_VERSION=16; values > 16 are invisible to the SQLite path).
    ``sql``: DDL to execute. Each ``;``-separated statement runs independently
        in autocommit mode via the raw psycopg connection (not the adapter),
        so SQLite-compat translation is bypassed. Do NOT embed ``;`` inside
        dollar-quoted (``$$``) blocks or single-quoted literals — the split
        is naive.
    ``optional``: If ``True``, any exception is logged at WARNING and the
        migration is skipped without recording the version (enabling retry on
        next connect). If ``False``, the exception propagates.
    """

    version: int
    sql: str
    optional: bool = False


_PG_ONLY_MIGRATIONS: List[PostgresMigration] = [
    # v17 — Install pg_trgm extension (required: failure retries next connect).
    # On Adam's Azure Flexible Server pg_trgm is already installed, so this is
    # a fast no-op. Non-optional so unexpected failure surfaces in logs.
    PostgresMigration(
        version=17,
        optional=False,
        sql="CREATE EXTENSION IF NOT EXISTS pg_trgm",
    ),
    # v18 — GIN trigram indexes on the three searched columns. optional=True
    # because index builds can fail transiently (lock, OOM, disk full); ILIKE
    # still works without them (just slower). IF NOT EXISTS makes this
    # idempotent so pre-created indexes on large production tables are skipped.
    PostgresMigration(
        version=18,
        optional=True,
        sql=(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_content_trgm"
            "    ON messages USING GIN (content gin_trgm_ops);\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_tool_name_trgm"
            "    ON messages USING GIN (tool_name gin_trgm_ops);\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_tool_calls_trgm"
            "    ON messages USING GIN (tool_calls gin_trgm_ops)"
        ),
    ),
]


def plan_postgres_migrations(current_version: int) -> List[PostgresMigration]:
    """Return pending Postgres-only migrations (version > *current_version*).

    *current_version* is sourced from ``schema_version`` ``MAX(version)`` —
    NOT from the upstream ``SCHEMA_VERSION`` constant, which governs only the
    SQLite/shared schema.
    """
    return [m for m in _PG_ONLY_MIGRATIONS if m.version > current_version]


def _probe_pg_trgm(conn: Any) -> bool:
    """Return ``True`` if pg_trgm is installed in the current database.

    TEST UTILITY — not called from the production path. Uses a catalog probe
    rather than ``try/except`` on DDL to avoid putting the psycopg connection
    into an aborted-transaction state.
    """
    try:
        row = conn.execute(
            "SELECT 1 FROM pg_catalog.pg_extension WHERE extname = 'pg_trgm'"
        ).fetchone()
        return row is not None
    except Exception:
        return False


def _apply_single_migration(conn: Any, migration: PostgresMigration) -> None:
    """Execute one migration's SQL and record the version.

    Executes against ``conn._conn`` (raw psycopg), NOT the ``_PostgresCursor``
    adapter, so migration DDL is not subject to SQLite-compat translation
    (``?`` → ``%s``, strict-mode checks, etc.).

    ``CREATE INDEX CONCURRENTLY`` requires the connection to be in autocommit
    mode. ``connect_postgres`` always opens with ``autocommit=True``, so each
    statement commits immediately — this is correct and required for
    CONCURRENTLY.

    The version INSERT runs last. If a prior statement fails the version is not
    recorded, so the migration retries on the next connect.
    """
    raw = conn._conn  # raw psycopg connection — bypass adapter translation
    for statement in migration.sql.split(";"):
        statement = statement.strip()
        if not statement:
            continue
        if "INDEX" in statement.upper():
            logger.info(
                "pg-only migration v%d: creating GIN index (may take a while"
                " on large tables): %.80s…",
                migration.version,
                statement,
            )
        raw.execute(statement)
    # Append-only version record. ON CONFLICT DO NOTHING makes a concurrent
    # second runner safe (both see version N, both try to insert — second wins
    # the race but the INSERT is a harmless no-op).
    raw.execute(
        "INSERT INTO schema_version (version) VALUES (%s) ON CONFLICT DO NOTHING",
        (migration.version,),
    )


def apply_postgres_migrations(conn: Any) -> None:
    """Apply any pending Postgres-only migrations.

    Called by :func:`init_postgres_schema` on every connect. Reads
    ``MAX(version)`` from ``schema_version`` and applies only migrations with
    version > current. Idempotent: safe to call repeatedly.

    Concurrent-connect race: safe. ``CREATE EXTENSION IF NOT EXISTS`` and
    ``CREATE INDEX CONCURRENTLY IF NOT EXISTS`` are idempotent; the version
    ``INSERT … ON CONFLICT DO NOTHING`` absorbs the duplicate.

    Optional migrations (``optional=True``) log a WARNING on failure without
    recording the version, enabling retry on next connect. Non-optional
    migrations propagate the exception.
    """
    current = postgres_schema_version(conn)
    pending = plan_postgres_migrations(current)
    if not pending:
        return
    for migration in pending:
        if migration.optional:
            try:
                _apply_single_migration(conn, migration)
                logger.info("pg-only migration v%d applied", migration.version)
            except Exception as exc:
                logger.warning(
                    "pg-only migration v%d skipped (optional): %s",
                    migration.version,
                    exc,
                )
        else:
            _apply_single_migration(conn, migration)
            logger.info("pg-only migration v%d applied", migration.version)


def init_postgres_schema(conn: Any, schema_version: int) -> None:
    """Create the PostgreSQL schema if absent, record the base schema version,
    and apply any pending Postgres-only migrations.

    Idempotent: every DDL statement uses ``IF NOT EXISTS``, and the base
    version row is only inserted when the table is empty. Postgres-only
    migrations (version > 16) are applied after the base schema is
    established; they use ``MAX(version)`` to determine what is pending.
    """
    cur = conn.cursor()
    cur.executescript(SCHEMA_SQL_POSTGRES)
    existing = cur.execute("SELECT version FROM schema_version LIMIT 1").fetchone()
    if existing is None:
        cur.execute("INSERT INTO schema_version (version) VALUES (?)", (schema_version,))
    conn.commit()
    # Apply Postgres-only migrations (e.g. pg_trgm GIN indexes). Version
    # numbers > 16 are invisible to the SQLite path and never conflict.
    apply_postgres_migrations(conn)


def postgres_schema_version(conn: Any) -> int:
    """Return the recorded schema version, or 0 if the schema is uninitialized."""
    try:
        row = conn.execute("SELECT MAX(version) AS version FROM schema_version").fetchone()
    except Exception:
        return 0
    if not row or row["version"] is None:
        return 0
    return int(row["version"])


# ---------------------------------------------------------------------------
# Thin cursor adapter
# ---------------------------------------------------------------------------
#
# Translates ONLY the small closed surface of SQLite idioms that SessionDB
# emits, so the existing class body runs unchanged. Anything outside this set
# passes through verbatim; in strict mode (HERMES_PG_ADAPTER_STRICT=1, set by
# the parity test) an unrecognized SQLite-only idiom raises instead of silently
# reaching PostgreSQL with surprising semantics.

import os
import re

_STRICT_ENV = "HERMES_PG_ADAPTER_STRICT"

# SQLite-only tokens that must never reach PostgreSQL untranslated. If strict
# mode is on and a statement still contains one of these after translation, the
# adapter raises — converting "unknown idiom slipped through" from a production
# surprise into a loud test failure.
_STRICT_FORBIDDEN = (
    "json_extract",
    "json_set",
    "autoincrement",
    "pragma",
    " glob ",
    "strftime",
    "fts5",
    "match ",
)


def _strict_enabled() -> bool:
    return os.environ.get(_STRICT_ENV, "").strip().lower() in ("1", "true", "yes", "on")


def _translate_sql(sql: str) -> str:
    """Rewrite the closed set of SQLite idioms to their PostgreSQL equivalents.

    The transformations, in order:
      * ``BEGIN IMMEDIATE`` -> ``BEGIN`` (the per-session advisory lock that
        restores serialization lives in the compression-lock method, not here).
      * ``INSERT OR IGNORE INTO t ...`` -> ``INSERT INTO t ... ON CONFLICT DO
        NOTHING``.
      * ``json_extract(COALESCE(<col>, '{}'), '$.<key>')`` -> PostgreSQL jsonb
        text access ``(COALESCE(<col>, '{}')::jsonb ->> '<key>')``. SessionDB
        emits this exact shape for the ``model_config`` markers (``_delegate_from``,
        ``_branched_from``) in session-listing / lineage / delegate-cleanup
        queries (hermes_state helpers ``_delegate_from_json`` /
        ``_ephemeral_child_sql``). Untranslated, these are invalid PostgreSQL and
        the session paths break.
      * ``?`` placeholders -> ``%s`` (psycopg paramstyle). String/identifier
        literals do not contain ``?`` in the SessionDB query set, so a direct
        replace is safe.
    """
    stripped = sql.strip()
    if stripped.upper() == "BEGIN IMMEDIATE":
        return "BEGIN"

    translated = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        sql,
        flags=re.IGNORECASE,
    )
    insert_or_ignore = translated is not sql and translated != sql

    # json_extract(COALESCE(<col>, '{}'), '$.<key>') -> jsonb text access.
    # The SessionDB call sites always wrap the column in COALESCE(...,'{}') and
    # use a top-level '$.<key>' path; we translate that closed shape rather than
    # general JSONPath. `<col>` may be qualified (e.g. s.model_config).
    translated = re.sub(
        r"json_extract\(\s*COALESCE\(\s*([A-Za-z_][\w.]*)\s*,\s*'\{\}'\s*\)\s*,\s*'\$\.([A-Za-z_]\w*)'\s*\)",
        r"(COALESCE(\1, '{}')::jsonb ->> '\2')",
        translated,
        flags=re.IGNORECASE,
    )

    translated = translated.replace("?", "%s")

    if insert_or_ignore and "ON CONFLICT" not in translated.upper():
        translated = translated.rstrip().rstrip(";")
        translated += " ON CONFLICT DO NOTHING"

    if _strict_enabled():
        lowered = translated.lower()
        for token in _STRICT_FORBIDDEN:
            if token in lowered:
                raise RuntimeError(
                    f"PostgreSQL adapter strict mode: untranslated SQLite-only "
                    f"idiom {token!r} in statement: {stripped[:160]}"
                )

    return translated


def _needs_returning_id(sql: str) -> bool:
    """True for message INSERTs that must synthesize ``RETURNING id`` so that
    ``cursor.lastrowid`` keeps working (PostgreSQL has no implicit lastrowid)."""
    head = sql.lstrip()[:40].upper()
    return head.startswith("INSERT INTO MESSAGES")


class _PostgresCursor:
    """Translate the small ``sqlite3.Cursor`` surface SessionDB relies on."""

    def __init__(self, cursor: Any):
        self._cursor = cursor
        self.lastrowid: Optional[int] = None

    def execute(self, sql: str, params: Any = ()):
        translated = _translate_sql(sql)
        want_id = _needs_returning_id(translated) and " RETURNING " not in translated.upper()
        if want_id:
            translated = translated.rstrip().rstrip(";") + " RETURNING id"
        self._cursor.execute(translated, params or ())
        if want_id:
            row = self._cursor.fetchone()
            self.lastrowid = row[0] if row else None
        return self

    def executescript(self, sql_script: str):
        """Run a multi-statement DDL/script. PostgreSQL's driver executes one
        statement per ``execute``; split on ``;`` and run the non-empty pieces.
        """
        for statement in sql_script.split(";"):
            statement = statement.strip()
            if statement:
                self.execute(statement)
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        if row is None:
            return None
        return _PostgresRow(self._columns(), tuple(row))

    def fetchall(self):
        cols = self._columns()
        return [_PostgresRow(cols, tuple(r)) for r in self._cursor.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())

    def _columns(self) -> List[str]:
        return [desc[0] for desc in (self._cursor.description or [])]

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount


class _PostgresRow:
    """A row that supports both ``row["col"]`` and ``row[0]`` plus ``keys()`` and
    ``dict(row)`` — the access patterns SessionDB uses on ``sqlite3.Row``."""

    def __init__(self, columns: List[str], values: Tuple[Any, ...]):
        self._columns = columns
        self._values = values
        self._map = dict(zip(columns, values))

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, str):
            return self._map[key]
        return self._values[key]

    def __contains__(self, key: Any) -> bool:
        return key in self._map

    def keys(self) -> List[str]:
        return list(self._columns)

    def get(self, key: str, default: Any = None) -> Any:
        return self._map.get(key, default)


class _PostgresConnection:
    """Adapter exposing the ``sqlite3.Connection`` surface SessionDB calls."""

    def __init__(self, conn: Any):
        self._conn = conn

    def cursor(self) -> _PostgresCursor:
        return _PostgresCursor(self._conn.cursor())

    def execute(self, sql: str, params: Any = ()) -> _PostgresCursor:
        return self.cursor().execute(sql, params)

    def executescript(self, sql_script: str) -> _PostgresCursor:
        return self.cursor().executescript(sql_script)

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()

    @property
    def raw(self) -> Any:
        """The underlying psycopg connection (for advisory-lock SQL etc.)."""
        return self._conn


def connect_postgres(database_url: str) -> _PostgresConnection:
    """Open a PostgreSQL connection wrapped in the SQLite-compatible adapter.

    The DSN is passed through unchanged, so the operator's connection string
    fully determines TLS mode, host, port, and credentials.
    """
    try:
        import psycopg
    except ImportError as exc:  # pragma: no cover - exercised via install state
        raise RuntimeError(
            "PostgreSQL state backend requires psycopg; install the 'postgres' "
            "extra (pip install 'hermes-agent[postgres]')"
        ) from exc
    return _PostgresConnection(psycopg.connect(database_url, autocommit=True))


# ---------------------------------------------------------------------------
# Backend resolution + open entrypoint
# ---------------------------------------------------------------------------

_ENV_DSN_KEYS = ("HERMES_STATE_DATABASE_URL", "HERMES_STATE_POSTGRES_DSN")
_ENV_BACKEND_KEYS = ("HERMES_STATE_BACKEND",)


def resolve_postgres_dsn(config: Optional[Dict[str, Any]] = None) -> Optional[str]:
    """Return the configured PostgreSQL DSN, or None when not selected.

    Resolution order, first non-empty wins:
      1. ``HERMES_STATE_DATABASE_URL`` / ``HERMES_STATE_POSTGRES_DSN`` env vars
      2. ``sessions.postgres_dsn`` in config.yaml

    Backend selection (must equal "postgres" to engage this module):
      1. ``HERMES_STATE_BACKEND`` env var
      2. ``sessions.state_backend`` in config.yaml

    Returns None when ``sessions.state_backend`` is not "postgres" (the default
    "sqlite" path), so callers can cheaply decide whether to engage this module.
    """
    if config is None:
        try:
            from hermes_cli.config import load_config

            config = load_config()
        except Exception:
            return None

    sessions_cfg = (config or {}).get("sessions") or {}

    # Check env var first, then config.yaml
    backend = ""
    for key in _ENV_BACKEND_KEYS:
        env_val = (os.environ.get(key) or "").strip()
        if env_val:
            backend = env_val
            break
    if not backend:
        backend = str(sessions_cfg.get("state_backend") or "sqlite").strip().lower()

    if backend in ("postgresql", "pg"):
        backend = "postgres"
    if backend != "postgres":
        return None

    for key in _ENV_DSN_KEYS:
        env_val = (os.environ.get(key) or "").strip()
        if env_val:
            return env_val
    dsn = (sessions_cfg.get("postgres_dsn") or "").strip()
    if not dsn:
        raise RuntimeError(
            "sessions.state_backend is 'postgres' but no DSN was provided; set "
            "sessions.postgres_dsn, HERMES_STATE_DATABASE_URL, or "
            "HERMES_STATE_POSTGRES_DSN"
        )
    return dsn


def maybe_open_postgres(
    read_only: bool,
    schema_version: int,
    config: Optional[Dict[str, Any]] = None,
) -> Optional[_PostgresConnection]:
    """Open the PostgreSQL backend if it is configured, else return None.

    Returns None (so the caller proceeds with SQLite) when:
      * the configured backend is not "postgres", or
      * ``read_only`` is requested — the read-only cross-profile attach path is
        SQLite-specific and intentionally not served by this backend.

    Otherwise opens the adapter connection, initializes the schema, and returns
    the live connection. Raises if the DSN is missing or psycopg is absent.
    """
    if read_only:
        return None
    dsn = resolve_postgres_dsn(config)
    if not dsn:
        return None
    conn = connect_postgres(dsn)
    init_postgres_schema(conn, schema_version)
    return conn


def is_postgres_retryable(exc: BaseException) -> bool:
    """True if a PostgreSQL exception is a transient serialization/deadlock that
    warrants the jittered write retry (the PG analogue of SQLite "locked").

    Identified by SQLSTATE class 40 (transaction rollback: 40001 serialization
    failure, 40P01 deadlock detected) when psycopg exposes ``sqlstate``, with a
    message-substring fallback. Returns False for any non-PostgreSQL exception
    so the caller re-raises unchanged.
    """
    sqlstate = getattr(exc, "sqlstate", None)
    if sqlstate in ("40001", "40P01"):
        return True
    msg = str(exc).lower()
    return "serialization failure" in msg or "deadlock detected" in msg


def acquire_compression_lock_sql(conn: Any, session_id: str, holder: str,
                                 now: float, expires_at: float) -> bool:
    """Acquire the per-session compression lock under a PostgreSQL transaction.

    ``conn`` is the adapter connection inside an active transaction (the caller's
    ``_execute_write`` has already issued BEGIN). Because PostgreSQL's default
    isolation does not take a whole-database write lock the way SQLite's
    ``BEGIN IMMEDIATE`` does, we first take a transaction-scoped advisory lock
    keyed on the session id. That advisory lock serializes the
    delete-expired / insert / confirm sequence per session and auto-releases at
    transaction end, so a crashed acquirer cannot leak it.
    """
    conn.execute("SELECT pg_advisory_xact_lock(hashtext(?))", (session_id,))
    conn.execute(
        "DELETE FROM compression_locks WHERE session_id = ? AND expires_at < ?",
        (session_id, now),
    )
    conn.execute(
        "INSERT OR IGNORE INTO compression_locks "
        "(session_id, holder, acquired_at, expires_at) VALUES (?, ?, ?, ?)",
        (session_id, holder, now, expires_at),
    )
    row = conn.execute(
        "SELECT holder FROM compression_locks WHERE session_id = ?",
        (session_id,),
    ).fetchone()
    return row is not None and row["holder"] == holder


# ---------------------------------------------------------------------------
# ILIKE search for the PostgreSQL backend (GIN-accelerated)
# ---------------------------------------------------------------------------
#
# PostgreSQL has no SQLite FTS5 equivalent. Search uses case-insensitive
# ILIKE over the same text columns the FTS5 index covers (content, tool_name,
# tool_calls). When pg_trgm is installed and the GIN indexes created by
# migrations v17/v18 are present, PostgreSQL uses them automatically —
# no query-syntax change needed. Without the indexes the query falls back
# to a sequential scan (slower but functionally identical).
# Queries shorter than 3 characters bypass the trigram index (fundamental
# trigram minimum); those fall back to seq scan as well.
#
# The result-row contract matches the SQLite search_messages
# path exactly (id/session_id/role/snippet/timestamp/tool_name/source/model/
# session_started + a bounded before/anchor/after ``context`` window, with the
# full ``content`` removed), so callers are backend-agnostic.

_SEARCH_CONTEXT_SQL = """
    WITH target AS (
        SELECT session_id, timestamp, id FROM messages WHERE id = ?
    )
    SELECT role, content FROM (
        SELECT m.id, m.timestamp, m.role, m.content
        FROM messages m JOIN target t ON t.session_id = m.session_id
        WHERE (m.timestamp < t.timestamp)
           OR (m.timestamp = t.timestamp AND m.id < t.id)
        ORDER BY m.timestamp DESC, m.id DESC LIMIT 1
    ) AS before_row
    UNION ALL
    SELECT role, content FROM messages WHERE id = ?
    UNION ALL
    SELECT role, content FROM (
        SELECT m.id, m.timestamp, m.role, m.content
        FROM messages m JOIN target t ON t.session_id = m.session_id
        WHERE (m.timestamp > t.timestamp)
           OR (m.timestamp = t.timestamp AND m.id > t.id)
        ORDER BY m.timestamp ASC, m.id ASC LIMIT 1
    ) AS after_row
"""


def _content_preview(decode_content, raw: Any) -> str:
    decoded = decode_content(raw)
    if isinstance(decoded, list):
        parts = [
            p.get("text", "") for p in decoded
            if isinstance(p, dict) and p.get("type") == "text"
        ]
        return " ".join(t for t in parts if t).strip() or "[multimodal content]"
    if isinstance(decoded, str):
        return decoded
    return ""


def search_messages_postgres(
    conn: Any,
    decode_content,
    query: str,
    source_filter: Optional[List[str]] = None,
    exclude_sources: Optional[List[str]] = None,
    role_filter: Optional[List[str]] = None,
    limit: int = 20,
    offset: int = 0,
    sort: Optional[str] = None,
    include_inactive: bool = False,
) -> List[Dict[str, Any]]:
    """ILIKE substring search for the PostgreSQL backend, GIN-accelerated when
    pg_trgm is installed (migrations v17/v18).

    Intentionally uses portable ILIKE semantics rather than emulating FTS5
    query syntax (boolean operators, prefix ``*``, phrase quoting). Matches the
    SQLite ``search_messages`` result contract so callers stay backend-agnostic.
    """
    if not query or not query.strip():
        return []

    # Escape LIKE metacharacters so a query containing % or _ matches literally.
    escaped = query.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
    like = f"%{escaped}%"

    where = [
        "(m.content ILIKE ? ESCAPE '\\' OR m.tool_name ILIKE ? ESCAPE '\\' "
        "OR m.tool_calls ILIKE ? ESCAPE '\\')"
    ]
    params: list = [like, like, like]
    if not include_inactive:
        where.append("m.active = 1")
    if source_filter is not None:
        where.append("s.source IN (%s)" % ",".join("?" for _ in source_filter))
        params.extend(source_filter)
    if exclude_sources is not None:
        where.append("s.source NOT IN (%s)" % ",".join("?" for _ in exclude_sources))
        params.extend(exclude_sources)
    if role_filter:
        where.append("m.role IN (%s)" % ",".join("?" for _ in role_filter))
        params.extend(role_filter)

    sort_norm = sort.strip().lower() if isinstance(sort, str) else None
    order_by = "ORDER BY m.timestamp ASC" if sort_norm == "oldest" else "ORDER BY m.timestamp DESC"
    params.extend([limit, offset])

    rows = conn.execute(
        f"""
        SELECT m.id, m.session_id, m.role, m.content, m.timestamp, m.tool_name,
               s.source, s.model, s.started_at AS session_started
        FROM messages m
        JOIN sessions s ON s.id = m.session_id
        WHERE {' AND '.join(where)}
        {order_by}
        LIMIT ? OFFSET ?
        """,
        params,
    ).fetchall()

    matches: List[Dict[str, Any]] = []
    for r in rows:
        preview = _content_preview(decode_content, r["content"])
        matches.append({
            "id": r["id"],
            "session_id": r["session_id"],
            "role": r["role"],
            "snippet": preview[:200],
            "timestamp": r["timestamp"],
            "tool_name": r["tool_name"],
            "source": r["source"],
            "model": r["model"],
            "session_started": r["session_started"],
        })

    # Bounded before/anchor/after context window, mirroring the SQLite path.
    for match in matches:
        try:
            ctx_rows = conn.execute(
                _SEARCH_CONTEXT_SQL, (match["id"], match["id"])
            ).fetchall()
            match["context"] = [
                {"role": r["role"],
                 "content": _content_preview(decode_content, r["content"])[:200]}
                for r in ctx_rows
            ]
        except Exception:
            match["context"] = []

    return matches


# ---------------------------------------------------------------------------
# Migration import primitives
# ---------------------------------------------------------------------------
#
# Backend-neutral import used by the one-shot SQLite -> PostgreSQL migration.
# Rows are written through the SAME encode chokepoint the live path uses
# (``encode_content``), so the migrated content carries the current sentinel and
# never a raw NUL byte. Message ids and timestamps are preserved for fidelity.

_SESSION_COLUMNS = [
    "id", "source", "user_id", "model", "model_config", "system_prompt",
    "parent_session_id", "started_at", "ended_at", "end_reason",
    "message_count", "tool_call_count", "input_tokens", "output_tokens",
    "cache_read_tokens", "cache_write_tokens", "reasoning_tokens", "cwd",
    "billing_provider", "billing_base_url", "billing_mode",
    "estimated_cost_usd", "actual_cost_usd", "cost_status", "cost_source",
    "pricing_version", "title", "api_call_count", "handoff_state",
    "handoff_platform", "handoff_error", "rewind_count", "archived",
]

_MESSAGE_COLUMNS = [
    "id", "session_id", "role", "content", "tool_call_id", "tool_calls",
    "tool_name", "timestamp", "token_count", "finish_reason", "reasoning",
    "reasoning_content", "reasoning_details", "codex_reasoning_items",
    "codex_message_items", "platform_message_id", "observed", "active",
]


def _json_for_storage(value: Any) -> Optional[str]:
    """Serialize a JSON-ish column to text for storage, leaving str/None as-is."""
    import json
    if value is None or isinstance(value, str):
        return value
    return json.dumps(value)


def import_session(conn: Any, decode_content, encode_content,
                   session_data: Dict[str, Any]) -> None:
    """Import one exported session (session row + its messages) into PostgreSQL.

    Idempotent for the intended fresh-target migration flow: rows are inserted
    with ``ON CONFLICT DO NOTHING``, so re-running after a partial run skips
    already-imported rows rather than duplicating them. (It does not overwrite an
    existing row whose source content later changed — the migration targets a
    fresh database, where that case does not arise.) Each message's content is
    normalized through ``decode_content`` then ``encode_content`` — the live
    read+write chokepoints — so any value still carrying the legacy NUL-byte
    sentinel is decoded to its native object and re-encoded with the current
    (NUL-free) sentinel. No NUL byte is ever written to PostgreSQL. Message
    ids/timestamps are preserved.
    """
    session_id = session_data["id"]
    messages = session_data.get("messages") or []

    placeholders = ", ".join("?" for _ in _SESSION_COLUMNS)
    # INSERT OR IGNORE -> ON CONFLICT DO NOTHING (via the adapter). The target is
    # a fresh database in the normal migration flow; conflict-ignore makes a
    # re-run idempotent without per-row DELETEs, which would otherwise trip the
    # self-referential sessions FK (a parent cannot be deleted while a child
    # still references it).
    conn.execute(
        f"INSERT OR IGNORE INTO sessions ({', '.join(_SESSION_COLUMNS)}) "
        f"VALUES ({placeholders})",
        tuple(session_data.get(col) for col in _SESSION_COLUMNS),
    )

    msg_placeholders = ", ".join("?" for _ in _MESSAGE_COLUMNS)
    for message in messages:
        row = dict(message)
        row["session_id"] = session_id
        # decode -> encode normalizes the stored sentinel (legacy NUL -> current)
        # and guarantees no NUL byte survives into PostgreSQL text.
        row["content"] = encode_content(decode_content(row.get("content")))
        for key in ("tool_calls", "reasoning_details", "codex_reasoning_items",
                    "codex_message_items"):
            row[key] = _json_for_storage(row.get(key))
        conn.execute(
            f"INSERT OR IGNORE INTO messages ({', '.join(_MESSAGE_COLUMNS)}) "
            f"VALUES ({msg_placeholders})",
            tuple(row.get(col) for col in _MESSAGE_COLUMNS),
        )

    # Keep the IDENTITY sequence ahead of the largest imported id so future
    # inserts don't collide with preserved ids.
    conn.execute(
        "SELECT setval(pg_get_serial_sequence('messages', 'id'), "
        "GREATEST((SELECT COALESCE(MAX(id), 1) FROM messages), 1), true)"
    )
    conn.commit()


def import_sessions(conn: Any, decode_content, encode_content,
                    sessions: List[Dict[str, Any]]) -> int:
    """Import many sessions, ordering parents before children for the FK.

    Returns the number of sessions imported. Sessions whose parent is absent
    from the batch are imported in a stable order so a broken lineage cannot
    block the migration indefinitely.
    """
    remaining = {s["id"]: s for s in sessions}
    imported: set = set()
    count = 0
    while remaining:
        ready = [
            sid for sid, s in remaining.items()
            if not s.get("parent_session_id")
            or s.get("parent_session_id") in imported
            or s.get("parent_session_id") not in remaining
        ]
        if not ready:
            ready = [sorted(remaining)[0]]
        for sid in ready:
            import_session(conn, decode_content, encode_content, remaining.pop(sid))
            imported.add(sid)
            count += 1
    return count
